### ISSUE TITLE
Using AngularDevise with SpreeAuthDevise

### ISSUE THREAD

**Issue by BenMorganIO** [cloudspace/angular_devise#42]
Currently, I am trying to get my custom spree application to work with AngularDevise.

In my ApplicationController:

```ruby
class ApplicationController < ActionController::Base
  respond_to :html, :json

  protect_from_forgery with: :exception
end
```

Module setup via:

```js
var DeviseModule = angular.module('DeviseModule', ["Devise"]);

$(document).on("ready page:load", function() {
  return angular.bootstrap("#devise", ["DeviseModule"]);
});
```

Configuration as so:

```coffee
DeviseModule.config (AuthProvider, AuthInterceptProvider) ->
  # Customize login
  AuthProvider.loginMethod "POST"
  AuthProvider.loginPath "/user/spree_user/sign_in.json"

  # Customize logout
  AuthProvider.logoutMethod "GET"
  AuthProvider.logoutPath "/user/spree_user/logout.json"

  # Customize register
  AuthProvider.registerMethod "PATCH"
  AuthProvider.registerPath "/user/spree_user.json"

  # Intercept 401 Unauthorized everywhere
  # Enables `devise:unauthorized` interceptor
  AuthInterceptProvider.interceptAuth true
  return
```

Rails routes:
```ruby
                        Prefix Verb   URI Pattern                              Controller#Action
                          root GET    /                                        spree/home#index
        new_spree_user_session GET    /user/spree_user/sign_in(.:format)       spree/user_sessions#new
            spree_user_session POST   /user/spree_user/sign_in(.:format)       spree/user_sessions#create
    destroy_spree_user_session GET    /user/spree_user/logout(.:format)        spree/user_sessions#destroy
           spree_user_password POST   /user/spree_user/password(.:format)      spree/user_passwords#create
       new_spree_user_password GET    /user/spree_user/password/new(.:format)  spree/user_passwords#new
      edit_spree_user_password GET    /user/spree_user/password/edit(.:format) spree/user_passwords#edit
                               PATCH  /user/spree_user/password(.:format)      spree/user_passwords#update
                               PUT    /user/spree_user/password(.:format)      spree/user_passwords#update
cancel_spree_user_registration GET    /user/spree_user/cancel(.:format)        spree/user_registrations#cancel
       spree_user_registration POST   /user/spree_user(.:format)               spree/user_registrations#create
   new_spree_user_registration GET    /user/spree_user/sign_up(.:format)       spree/user_registrations#new
  edit_spree_user_registration GET    /user/spree_user/edit(.:format)          spree/user_registrations#edit
                               PATCH  /user/spree_user(.:format)               spree/user_registrations#update
                               PUT    /user/spree_user(.:format)               spree/user_registrations#update
                               DELETE /user/spree_user(.:format)               spree/user_registrations#destroy
```

And the Login Controller currently looks like this:

```coffee
DeviseModule.controller "LoginController", ["$scope", "Auth", ($scope, Auth) ->
  credentials = {
    email: 'spree@example.com',
    password: 'spree123'
  }

  Auth.login(credentials).then ((user) ->
    console.log(user); # => {id: 1, ect: '...'}
  ), (error) ->
    # Authentication failed...
]
```

And the html its working with:

```haml
#devise
  %section{"ng-controller" => "LoginController"}
```

The issue that I'm seeing is the response from Devise:

```
17:49:50 web.1    | Started POST "/user/spree_user/sign_in.json" for 127.0.0.1 at 2015-01-06 17:49:50 -0500
17:49:50 web.1    | Processing by Spree::UserSessionsController#create as JSON
17:49:50 web.1    |   Parameters: {"user"=>{"email"=>"spree@example.com", "password"=>"[FILTERED]"}, "user_session"=>{"user"=>{"email"=>"spree@example.com", "password"=>"[FILTERED]"}}}
17:49:50 web.1    | Completed 406 Not Acceptable in 12ms
17:49:50 web.1    |
17:49:50 web.1    | ActionController::UnknownFormat - ActionController::UnknownFormat:
17:49:50 web.1    |   actionpack (4.1.9) lib/action_controller/metal/mime_responds.rb:440:in `retrieve_collector_from_mimes'
17:49:50 web.1    |   actionpack (4.1.9) lib/action_controller/metal/mime_responds.rb:256:in `respond_to'
17:49:50 web.1    |    () Users/benmorgan/.rvm/gems/ruby-2.2.0/bundler/gems/spree_auth_devise-4342275c04f0/lib/controllers/frontend/spree/user_sessions_controller.rb:32:in `create'
17:49:50 web.1    |   actionpack (4.1.9) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
17:49:50 web.1    |   actionpack (4.1.9) lib/abstract_controller/base.rb:189:in `process_action'
17:49:50 web.1    |   actionpack (4.1.9) lib/action_controller/metal/rendering.rb:10:in `process_action'
17:49:50 web.1    |   actionpack (4.1.9) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
17:49:50 web.1    |   activesupport (4.1.9) lib/active_support/callbacks.rb:113:in `call'
17:49:50 web.1    |   activesupport (4.1.9) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
17:49:50 web.1    |   activesupport (4.1.9) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
17:49:50 web.1    |   activesupport (4.1.9) lib/active_support/callbacks.rb:166:in `block in halting'
17:49:50 web.1    |   activesupport (4.1.9) lib/active_support/callbacks.rb:166:in `block in halting'
17:49:50 web.1    |   activesupport (4.1.9) lib/active_support/callbacks.rb:229:in `block in halting'
17:49:50 web.1    |   activesupport (4.1.9) lib/active_support/callbacks.rb:166:in `block in halting'
17:49:50 web.1    |   activesupport (4.1.9) lib/active_support/callbacks.rb:166:in `block in halting'
17:49:50 web.1    |   activesupport (4.1.9) lib/active_support/callbacks.rb:166:in `block in halting'
17:49:50 web.1    |   activesupport (4.1.9) lib/active_support/callbacks.rb:229:in `block in halting'
17:49:50 web.1    |   activesupport (4.1.9) lib/active_support/callbacks.rb:166:in `block in halting'
17:49:50 web.1    |   activesupport (4.1.9) lib/active_support/callbacks.rb:166:in `block in halting'
17:49:50 web.1    |   activesupport (4.1.9) lib/active_support/callbacks.rb:229:in `block in halting'
17:49:50 web.1    |   activesupport (4.1.9) lib/active_support/callbacks.rb:166:in `block in halting'
17:49:50 web.1    |   activesupport (4.1.9) lib/active_support/callbacks.rb:166:in `block in halting'
17:49:50 web.1    |   activesupport (4.1.9) lib/active_support/callbacks.rb:166:in `block in halting'
17:49:50 web.1    |   activesupport (4.1.9) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
17:49:50 web.1    |   activesupport (4.1.9) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
17:49:50 web.1    |   activesupport (4.1.9) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
17:49:50 web.1    |   activesupport (4.1.9) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
17:49:50 web.1    |   activesupport (4.1.9) lib/active_support/callbacks.rb:86:in `run_callbacks'
17:49:50 web.1    |   actionpack (4.1.9) lib/abstract_controller/callbacks.rb:19:in `process_action'
17:49:50 web.1    |   actionpack (4.1.9) lib/action_controller/metal/rescue.rb:29:in `process_action'
17:49:50 web.1    |   actionpack (4.1.9) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
17:49:50 web.1    |   activesupport (4.1.9) lib/active_support/notifications.rb:159:in `block in instrument'
17:49:50 web.1    |   activesupport (4.1.9) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
17:49:50 web.1    |   activesupport (4.1.9) lib/active_support/notifications.rb:159:in `instrument'
17:49:50 web.1    |   actionpack (4.1.9) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
17:49:50 web.1    |   actionpack (4.1.9) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
17:49:50 web.1    |   activerecord (4.1.9) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
17:49:50 web.1    |   actionpack (4.1.9) lib/abstract_controller/base.rb:136:in `process'
17:49:50 web.1    |   actionview (4.1.9) lib/action_view/rendering.rb:30:in `process'
17:49:50 web.1    |   actionpack (4.1.9) lib/action_controller/metal.rb:196:in `dispatch'
17:49:50 web.1    |   actionpack (4.1.9) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
17:49:50 web.1    |   actionpack (4.1.9) lib/action_controller/metal.rb:232:in `block in action'
17:49:50 web.1    |   actionpack (4.1.9) lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
17:49:50 web.1    |   actionpack (4.1.9) lib/action_dispatch/routing/route_set.rb:50:in `call'
17:49:50 web.1    |   actionpack (4.1.9) lib/action_dispatch/routing/mapper.rb:45:in `call'
17:49:50 web.1    |   actionpack (4.1.9) lib/action_dispatch/journey/router.rb:73:in `block in call'
17:49:50 web.1    |   actionpack (4.1.9) lib/action_dispatch/journey/router.rb:59:in `call'
17:49:50 web.1    |   actionpack (4.1.9) lib/action_dispatch/routing/route_set.rb:685:in `call'
17:49:50 web.1    |   bullet (4.13.2) lib/bullet/rack.rb:12:in `call'
17:49:50 web.1    |   meta_request (0.3.4) lib/meta_request/middlewares/app_request_handler.rb:13:in `call'
17:49:50 web.1    |   meta_request (0.3.4) lib/meta_request/middlewares/meta_request_handler.rb:13:in `call'
17:49:50 web.1    |   warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
17:49:50 web.1    |   warden (1.2.3) lib/warden/manager.rb:34:in `call'
17:49:50 web.1    |   rack (1.5.2) lib/rack/etag.rb:23:in `call'
17:49:50 web.1    |   rack (1.5.2) lib/rack/conditionalget.rb:35:in `call'
17:49:50 web.1    |   rack (1.5.2) lib/rack/head.rb:11:in `call'
17:49:50 web.1    |   actionpack (4.1.9) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
17:49:50 web.1    |   actionpack (4.1.9) lib/action_dispatch/middleware/flash.rb:254:in `call'
17:49:50 web.1    |   rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
17:49:50 web.1    |   rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
17:49:50 web.1    |   actionpack (4.1.9) lib/action_dispatch/middleware/cookies.rb:562:in `call'
17:49:50 web.1    |   activerecord (4.1.9) lib/active_record/query_cache.rb:36:in `call'
17:49:50 web.1    |   activerecord (4.1.9) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
17:49:50 web.1    |   activerecord (4.1.9) lib/active_record/migration.rb:380:in `call'
17:49:50 web.1    |   actionpack (4.1.9) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
17:49:50 web.1    |   activesupport (4.1.9) lib/active_support/callbacks.rb:82:in `run_callbacks'
17:49:50 web.1    |   actionpack (4.1.9) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
17:49:50 web.1    |   actionpack (4.1.9) lib/action_dispatch/middleware/reloader.rb:73:in `call'
17:49:50 web.1    |   actionpack (4.1.9) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
17:49:50 web.1    |   better_errors (2.0.0) lib/better_errors/middleware.rb:84:in `protected_app_call'
17:49:50 web.1    |   better_errors (2.0.0) lib/better_errors/middleware.rb:79:in `better_errors_call'
17:49:50 web.1    |   better_errors (2.0.0) lib/better_errors/middleware.rb:57:in `call'
17:49:50 web.1    |   rack-contrib (1.1.0) lib/rack/contrib/response_headers.rb:17:in `call'
17:49:50 web.1    |   meta_request (0.3.4) lib/meta_request/middlewares/headers.rb:16:in `call'
17:49:50 web.1    |   actionpack (4.1.9) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
17:49:50 web.1    |   actionpack (4.1.9) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
17:49:50 web.1    |   railties (4.1.9) lib/rails/rack/logger.rb:38:in `call_app'
17:49:50 web.1    |   railties (4.1.9) lib/rails/rack/logger.rb:20:in `block in call'
17:49:50 web.1    |   activesupport (4.1.9) lib/active_support/tagged_logging.rb:68:in `block in tagged'
17:49:50 web.1    |   activesupport (4.1.9) lib/active_support/tagged_logging.rb:26:in `tagged'
17:49:50 web.1    |   activesupport (4.1.9) lib/active_support/tagged_logging.rb:68:in `tagged'
17:49:50 web.1    |   railties (4.1.9) lib/rails/rack/logger.rb:20:in `call'
17:49:50 web.1    |   request_store (1.1.0) lib/request_store/middleware.rb:8:in `call'
17:49:50 web.1    |   actionpack (4.1.9) lib/action_dispatch/middleware/request_id.rb:21:in `call'
17:49:50 web.1    |   rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
17:49:50 web.1    |   rack (1.5.2) lib/rack/runtime.rb:17:in `call'
17:49:50 web.1    |   rack (1.5.2) lib/rack/lock.rb:17:in `call'
17:49:50 web.1    |   rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
17:49:50 web.1    |   rack-cache (1.2) lib/rack/cache/context.rb:143:in `pass'
17:49:50 web.1    |   rack-cache (1.2) lib/rack/cache/context.rb:155:in `invalidate'
17:49:50 web.1    |   rack-cache (1.2) lib/rack/cache/context.rb:71:in `call!'
17:49:50 web.1    |   rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
17:49:50 web.1    |   actionpack (4.1.9) lib/action_dispatch/middleware/static.rb:84:in `call'
17:49:50 web.1    |   rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
17:49:50 web.1    |   railties (4.1.9) lib/rails/engine.rb:514:in `call'
17:49:50 web.1    |   railties (4.1.9) lib/rails/application.rb:144:in `call'
17:49:50 web.1    |   rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
17:49:50 web.1    |   rack-cache (1.2) lib/rack/cache/context.rb:143:in `pass'
17:49:50 web.1    |   rack-cache (1.2) lib/rack/cache/context.rb:155:in `invalidate'
17:49:50 web.1    |   rack-cache (1.2) lib/rack/cache/context.rb:71:in `call!'
17:49:50 web.1    |   rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
17:49:50 web.1    |   rack (1.5.2) lib/rack/content_length.rb:14:in `call'
17:49:50 web.1    |   puma (2.9.1) lib/puma/server.rb:490:in `handle_request'
17:49:50 web.1    |   puma (2.9.1) lib/puma/server.rb:361:in `process_client'
17:49:50 web.1    |   puma (2.9.1) lib/puma/server.rb:254:in `block in run'
17:49:50 web.1    |   puma (2.9.1) lib/puma/thread_pool.rb:92:in `block in spawn_thread'
17:49:50 web.1    |   logging (1.8.2) lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
```

So, I decided to make `Spree::UserSessionsController` respond to JSON:

```
Spree::UserSessionsController.class_eval do
  respond_to :html, :json
end
```

Still no luck. The create method can be seen [here](https://github.com/spree/spree_auth_devise/blob/master/lib/controllers/frontend/spree/user_sessions_controller.rb#L16-L42). It does seem to be able to respond to JSON.

**Comment by jridgewell** [comment]
> Response is actually already in json. They're literally calling #to_json at the end.

I wasn't sure if Angular would parse the JSON string into an object without `Content-Type: application/json`. If it works already, sweet.

> Is there a way to change the params for AngularDevise to match Spree's?

Use `AuthProvider.resourceName('spree_user')`.

**Comment by BenMorganIO** [comment]
Merci.
